version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "miniforge3-latest"

conda:
  environment: environment.yml

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
