name: Build/Test CI

on: [push, pull_request]

jobs:

  build-and-test:

    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          environment-file: environment.yml
          activate-environment: geotiff
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Show conda installation info
        run: |
          conda info
          conda list

      - name: Install package
        run: pip install -e .

      - name: Test
        run: |
          nox -s test --python ${{ matrix.python-version }}

      - name: Test BMI
        if: ${{ matrix.python-version == '3.11' }}
        run: |
          nox -s test-bmi --python ${{ matrix.python-version }}

      - name: Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        uses: AndreMiras/coveralls-python-action@develop
