name: Format

on: [push, pull_request]

jobs:

  format:
    name: Check for lint and format code to a standard style
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          python-version: 3.11
          auto-activate-base: false

      - name: Install nox
        run: pip install nox

      - name: Format code
        run: nox -s format -- --check --verbose --diff
