name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '51 4 3 * *'  # 4:51a on third day of the month

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  test:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install nox
        run: pip install nox

      - name: Test
        run: |
          nox -s test --python ${{ matrix.python-version }}

      - name: Test BMI
        if: ${{ matrix.python-version == '3.12' }}
        run: |
          nox -s test-bmi --python ${{ matrix.python-version }}

      - name: Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
        uses: AndreMiras/coveralls-python-action@develop
